# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oSJyXmNRNgE0Z0RszQn7NJgb44tD5POO
"""

import csv  
    
# field names  
fields = ['Name', 'Frontline Worker', 'Age', 'Pregnant', 'Comorbidity']  
    
# data rows of csv file  
rows = [ ['Nikhil', 'yes', '65', 'no','no'],  
         ['Sanchit', 'no', '41', 'no','yes'],  
         ['Aditya', 'no', '25', 'no','no'],  
         ['Sagar', 'yes', '70', 'no','yes'],  
         ['Prateek', 'no', '42', 'no','yes'],
         ['Raghav', 'yes','12','no','yes'],
         ['Sujata', 'yes','32','no','no'],
         ['Laxman', 'no','74','no','no'],
         ['Rohan', 'no','68','no','no'],
         ['Mishti', 'yes','33','yes','no'],
         ['Abhinav', 'yes','26','no','yes'],
         ['Neelanchi', 'yes','77','no','yes'], 
         ['Vrinda', 'no','45','no','no'], 
         ['Sumukhi', 'yes', '34', 'yes','no']]  
    
# name of csv file  
filename = "population_records1.csv"
    
# writing to csv file  
with open(filename, 'w') as csvfile:  
    # creating a csv writer object  
    csvwriter = csv.writer(csvfile)  
        
    # writing the fields  
    csvwriter.writerow(fields)  
        
    # writing the data rows  
    csvwriter.writerows(rows)

import pandas as pd 
import numpy as np
  
# load csv file 
df = pd.read_csv("population_records1.csv") 
  
# replace the ‘commissioned' column  
# contains the values 'yes' and 'no' 
#  with True and  False: 
df = df.replace({'Comorbidity': {'yes': 5,  
                                'no': 0}})
df = df.replace({'Frontline Worker': {'yes': 10,  
                                'no': 0}})
df = df.replace({'Pregnant': {'yes': 5,  
                                'no': 0}}) 
df['Age'] = np.where((df.Age < 50), 10, 0)


df['Score'] = df['Frontline Worker'] + df['Age'] + df['Pregnant'] + df['Comorbidity']
df=df.sort_values(by=['Score'], ascending=False)
  
# show the dataframe 
df